### ISSUE TITLE
matplotlib plots not showing but VCS are

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#289] opened 2016-01-28 18:28 UTC
@durack1 @doutriaux1 Just did a new build with latest install script with graphics options below.   Both VCS and matplot lib can be loaded and VCS plotting working normally.   Matplotlib still remains invisible even with mesa false...
Any hints?

## Do we want to build with graphics capabilities
build_graphics=true  #false
## Do we want MESA driver (non-interactive graphics mode)
build_graphics_against_mesa=false

**Comment by durack1** [comment] 2016-01-28 18:44
@gleckler1 works for me in a non-metrics build:
```
>>> """
... Simple demo of a horizontal bar chart.
... """
'\nSimple demo of a horizontal bar chart.\n'
>>> import matplotlib.pyplot as plt; plt.rcdefaults()
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>>
>>>
>>> # Example data
... people = ('Tom', 'Dick', 'Harry', 'Slim', 'Jim')
>>> y_pos = np.arange(len(people))
>>> performance = 3 + 10 * np.random.rand(len(people))
>>> error = np.random.rand(len(people))
>>>
>>> plt.barh(y_pos, performance, xerr=error, align='center', alpha=0.4)
<Container object of 5 artists>
>>> plt.yticks(y_pos, people)
([<matplotlib.axis.YTick object at 0x7fe9b1e40e90>, <matplotlib.axis.YTick object at 0x7fe9b1e40dd0>, <matplotlib.axis.YTick object at 0x7fe9b1daead0>, <matplotlib.axis.YTick object at 0x7fe9b1d72690>, <matplotlib.axis.YTick object at 0x7fe9b1d72dd0>], <a list of 5 Text yticklabel objects>)
>>> plt.xlabel('Performance')
<matplotlib.text.Text object at 0x7fe9c3ab3c50>
>>> plt.title('How fast do you want to go today?')
<matplotlib.text.Text object at 0x7fe9b1df85d0>
>>>
>>> plt.show()
```

**Comment by durack1** [comment] 2016-01-28 19:36
@gleckler1 can we close this?

**Comment by gleckler1** [comment] 2016-01-28 20:02
@durack1 does not work for me on metrics build...

**Comment by durack1** [comment] 2016-01-28 21:43
@gleckler1 I can confirm I also have the same issue.. I am able to plot an item and save it using matplotlib, but `plt.show()` doesn't lead to a canvas appearing on the screen.

VCS appears to work as expected.

**Closed** 2016-05-25 00:33 UTC
Labels: Status Unclear
