### ISSUE TITLE
Possible issues with units

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#304] opened 2016-02-22 23:06 UTC
This section of the driver raises errors that I don't understand:
```
                                   raise RuntimeError(
                                       "Could not convert model units (%s) "
                                       "to obs units: (%s)" %
                                       (dm.units, do.units)
                                       )
```
Like this one:
```
 Error while processing variable tos:
	not all arguments converted during string formatting
```
I've ran the package after neutralizing these lines (with a #), and the result looks just fine. There is something at the beginning of this section that got my attention:
```
                            # Ok possible issue with units
```

The package is working for me right now but would you have some inputs for me on this point?

**Comment by durack1** [comment] 2016-04-05 22:41
@jservonnat we're starting to clean things up for a new release, if you are not able to reproduce this we'll close it (along with any other rogue issues)

**Comment by durack1** [comment] 2016-04-25 23:11
@jservonnat any more info on this? If not we'll close it as we're starting to clean things up for a new release

**Closed** 2016-05-25 00:29 UTC
Labels: Status Unclear
