### ISSUE TITLE
setup.py needs to reflect reorg of demo dir

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#371] opened 2016-07-01 17:24 UTC
@doutriaux1 @durack1 We've changed the organization of the demo directory in the source codes but not the binaries.   setup.py needs to be modified to reflect this.   PG will try...

**Comment by durack1** [comment] 2016-07-09 00:18
@gleckler1 @doutriaux1 this is a dupe of #374 so closing

**Closed by durack1** 2016-07-09 00:18 UTC
