### ISSUE TITLE
osx-arm64 not natively supported

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#932] opened 2023-05-24 03:30 UTC
I just attempted to install `pcmdi_metrics` using the conda-forge channel release:

```python
(base) paully@airy2 ~ % mamba create --dry-run -n pmp -c conda-forge pcmdi_metrics

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['pcmdi_metrics']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
Could not solve for environment specs
The following package could not be installed
└─ pcmdi_metrics   is uninstallable because it requires
   └─ cdms2  , which does not exist (perhaps a missing channel).
```

**Comment by durack1** [comment] 2023-05-24 03:32
It seems a switchout to `xcdat` would be very useful for cross-platform support

```python
(base) paully@airy2 ~ % mamba create --dry-run -n xcdat -c conda-forge xcdat   

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['xcdat']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
Transaction

  Prefix: /Users/paully/mambaforge/envs/xcdat

  Updating specs:

   - xcdat


  Package                    Version  Build                    Channel                     Size
─────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────────────────────

  + arrow-cpp                 12.0.0  hce30654_1_cpu           conda-forge/osx-arm64       29kB
...
  + xarray                  2023.5.0  pyhd8ed1ab_0             conda-forge/noarch         673kB
  + xcdat                      0.5.0  pyhd8ed1ab_0             conda-forge/noarch        Cached
...
  + zstd                       1.5.2  hf913c23_6               conda-forge/osx-arm64     Cached

  Summary:

  Install: 137 packages

  Total download: 166MB

─────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by durack1** [comment] 2023-05-24 03:34
this is dupe of #923

**Comment by lee1043** [comment] 2023-06-10 02:28
I am closing this as it is a duplicate of #923

**Closed by lee1043** 2023-06-10 02:28 UTC
Labels: duplicate
