### ISSUE TITLE
mismatch in src and dst data types (float32 vs float32)

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#305] opened 2016-02-24 15:55 UTC
I've had a new error when trying to get the model data:
```
>>> dm = MODEL.get(var,varInFile=varInFile)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs5r/workgpfs/rech/psl/rpsl035/PCMDI-MP/work_install_v3/PCMDI_METRICS/lib/python2.7/site-packages/pcmdi_metrics/io/base.py", line 51, in get
    periodicity=1)
  File "/gpfs5r/workgpfs/rech/psl/rpsl035/PCMDI-MP/work_install_v3/PCMDI_METRICS/lib/python2.7/site-packages/cdms2/avariable.py", line 1118, in regrid
    return ro(self, **keywords)
  File "/gpfs5r/workgpfs/rech/psl/rpsl035/PCMDI-MP/work_install_v3/PCMDI_METRICS/lib/python2.7/site-packages/cdms2/mvCdmsRegrid.py", line 440, in __call__
    **args)
  File "/gpfs5r/workgpfs/rech/psl/rpsl035/PCMDI-MP/work_install_v3/PCMDI_METRICS/lib/python2.7/site-packages/regrid2/mvGenericRegrid.py", line 253, in apply
    rootPe = rootPe, globalIndexing = True, **args)
  File "/gpfs5r/workgpfs/rech/psl/rpsl035/PCMDI-MP/work_install_v3/PCMDI_METRICS/lib/python2.7/site-packages/regrid2/mvLibCFRegrid.py", line 67, in apply
    self.regridObj.apply(srcData, dstData, missingValue)
  File "/gpfs5r/workgpfs/rech/psl/rpsl035/PCMDI-MP/work_install_v3/PCMDI_METRICS/lib/python2.7/site-packages/regrid2/gsRegrid.py", line 616, in apply
    % (__FILE__, src_data.dtype, dst_data.dtype)
regrid2.error.RegridError: ERROR in /gpfs5r/workgpfs/rech/psl/rpsl035/PCMDI-MP/work_install_v3/PCMDI_METRICS/lib/python2.7/site-packages/regrid2/gsRegrid.py: mismatch in src and dst data types (float32 vs float32)
```
Looks a bit weird to me, float32 vs float32 doesn't sound like a mismatch! Any suggestion?

**Comment by doutriaux1** [comment] 2016-03-03 16:48
@jservonnat which model/obs? Can you send a link?

**Comment by durack1** [comment] 2016-04-05 22:40
@jservonnat we're starting to clean things up for a new release, if you are not able to reproduce this we'll close it (along with any other rogue issues)

**Comment by durack1** [comment] 2016-04-25 23:11
@jservonnat any more info on this? If not we'll close it as we're starting to clean things up for a new release

**Comment by durack1** [comment] 2016-05-25 01:28
@jservonnat closing this

**Closed by durack1** 2016-05-25 01:28 UTC
Labels: Status Unclear
