### ISSUE TITLE
rectangular sub global ?

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#361] opened 2016-06-09 16:41 UTC
@doutriaux1 
Not remembering if this is implemented... don't see it on 
https://github.com/PCMDI/pcmdi_metrics/blob/master/doc/parameter_files/input_parameter_file_all_options.py

If its there, great, we'll use it now.   If not, can it be implemented toute suite?  NCAR is interested in it now... if not there or possible to do fast it will be fine to just add to v1.2 list

**Comment by gleckler1** [comment] 2016-06-30 01:49
@doutriaux1 This is an enhancement that we should put at the top of the list - being able to define a rectangular domain in the parameter file.   Is it already partly implemented??

**Comment by doutriaux1** [comment] 2016-06-30 13:52
@gleckler1 you mean sub-regions? Like EL-Nino at such?

**Comment by gleckler1** [comment] 2016-06-30 18:21
@doutriaux1   Yes!  
While your at it, you could hijack what has been started on a branch and put it where you think it belongs...
https://github.com/PCMDI/pcmdi_metrics/blob/334_monsoon_wang/src/python/devel/monsoon_wang/lib/PMP_rectangular_domains.py (pcmdi/scripts ?).

**Comment by gleckler1** [comment] 2016-07-01 14:26
@doutriaux1 I don't see branch to test this... is it hidden somewhere?

**Comment by gleckler1** [comment] 2016-07-07 21:37
@doutriaux1 can't find your test branch!?

**Comment by durack1** [comment] 2016-07-14 01:30
@doutriaux1 @gleckler1 I believe #252 is a dupe of this issue - I suggest closing both when the rectangular region specification is working

**Closed** 2016-07-18 22:46 UTC
Labels: HIPRIORITY
