### ISSUE TITLE
adding the variable in the json file

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#226] opened 2015-01-23 17:08 UTC
This to ease the automatic read of the content of a json file.

**Comment by durack1** [comment] 2016-07-14 15:00
@doutriaux1 @gleckler1 I think this is another dupe of an existing PR?

**Comment by durack1** [comment] 2016-07-14 22:17
duplicate of #369, closing

**Closed by durack1** 2016-07-14 22:17 UTC
